### 1 Numpy基础

In [2]:
import numpy as np

a = np.array([1, 2, 3])  # 创建一维数组
print(type(a))            # 打印类型
print(a.shape)            # 打印数组形状
print(a[0], a[1], a[2])   # 打印数组元素
a[0] = 5                 # 改变元素取值
print(a)                  # 打印整个数组


(2, 3)
1 2 4


In [3]:

b = np.array([[1,2,3],[4,5,6]])   # 创建二维数组
print(b.shape)                     # 形状
print(b[0, 0], b[0, 1], b[1, 0])   # 打印数组元素


(2, 3)
1 2 4


In [6]:
#numpy的数据类型设置
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype,arr1,end="\t")
print(arr2.dtype,arr2)

float64 [1. 2. 3.]	int32 [1 2 3]


In [3]:
#类型转换
arr=np.array([1,2,3])
print(arr.dtype)

float_arr=arr.astype(np.float64)
print(float_arr.dtype)

int64
float64


In [8]:
#索引和切片
arr = np.arange(10)
print(arr)
arr_slice = arr[5:8:2]
print(arr_slice)
arr_slice[1] = 999
print(arr_slice)

arr_slice[:] = 14
print(arr_slice)


[0 1 2 3 4 5 6 7 8 9]
[5 7]
[  5 999]
[14 14]


In [18]:
# 利用布尔数组切片
names = np.array(['Bob', 'Will', 'Bob', 'Joe'])
data = np.array([[-3, 2, 0, -1], [1, 2, 3, -4],
                 [2.5, 1.7, -0.2, 1], [-8, -4, 9, 10]])

print(names == 'Bob')
print(data[names == 'Bob'])
print(data[names == 'Bob', 2:])


[ True False  True False]
[[-3.   2.   0.  -1. ]
 [ 2.5  1.7 -0.2  1. ]]
[[ 0.  -1. ]
 [-0.2  1. ]]


In [10]:
# 基本统计方法
arr = np.arange(20).reshape((4,5))
print(arr)
print(arr.mean()) # 求均值
print(arr.sum()) # 求和
print(arr.mean(axis = 1)) # 沿列求均值
print(arr.sum(axis = 0)) # 沿行求和

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
9.5
190
[  2.   7.  12.  17.]
[30 34 38 42 46]


In [ ]:
# 正态分布采样
samples = np.random.normal(size=(2,3))
print(samples)


本案例使用lendingclub的公开数据集，完整数据集参考[Kaggle竞赛:Lending Club Loan Data](https://www.kaggle.com/wendykan/lending-club-loan-data)简要介绍pandas用于数据分析的方法和步骤。

数据集为贷款用户数据，有以下属性

|loan_amnt|grade|sub_grade|emp_length|home_onwership|annual_inc|issue_d|loan_status|open_acc|total_pymnt|total_rec_int|
|:---:|:---:|:---:|:---:|:---:|:---:|
|贷款数额|评级|评级细分|工作年限|是否拥有房屋|年收入|发贷日期|贷款状态|开户数量|还款总额|还贷利息总额

In [2]:
import numpy as np
import pandas as pd

In [87]:
# 读入数据
loan_data = pd.read_csv('./data/loandata.csv')
print(loan_data.head(10))

   loan_amnt grade sub_grade emp_length home_ownership  annual_inc  \
0     5000.0     B        B2  10+ years           RENT     24000.0   
1     2500.0     C        C4   < 1 year           RENT     30000.0   
2    12500.0     D        D4  10+ years           RENT     74400.0   
3    14000.0     A        A4  10+ years           RENT     72000.0   
4    35000.0     F        F5    4 years       MORTGAGE    100000.0   
5    16000.0     C        C2  10+ years            OWN         NaN   
6    14125.0     B        B5  10+ years            OWN     60000.0   
7     5000.0     B        B2    4 years           RENT     49000.0   
8     6000.0     A        A5  10+ years       MORTGAGE     48000.0   
9    12000.0     C        C3   < 1 year       MORTGAGE     81996.0   

      issue_d  loan_status  open_acc   total_pymnt  total_rec_int  
0  2017/12/11   Fully Paid         3   5863.155187         863.16  
1  2017/12/11  Charged Off         3   1014.530000         435.17  
2  2017/11/11   Fully Pai

### 2 Series和DataFrame

In [4]:
# Series对象
amnt_series = loan_data['loan_amnt']
print(type(amnt_series))
# dataframe对象
print(type(loan_data))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [50]:
# 创建dataframe对象 - 字典传入
data = {'method':['decision tree','svm'],'f1_score':[0.73,0.89]}
df = pd.DataFrame(data)
print(df)

   f1_score         method
0      0.73  decision tree
1      0.89            svm


In [51]:
df.rename(columns={'method':'algorithm'},inplace=True)# 更改列名
print(df)

   f1_score      algorithm
0      0.73  decision tree
1      0.89            svm


### 3 索引、选取、过滤、排序

In [24]:
print(df.iloc[1])# 获取某一行
print(df['method'])# 获取某一列
print(df.drop(0,axis=0))# drop 丢弃某一行 或 某一列 
print(df.drop('method',axis=1))

f1_score    0.89
method       svm
Name: 1, dtype: object
0    decision tree
1              svm
Name: method, dtype: object
   f1_score method
1      0.89    svm
   f1_score
0      0.73
1      0.89


In [25]:
df.drop(0,axis=0,inplace=True)# 丢弃之后更新dataframe
print(df)

   f1_score method
1      0.89    svm


In [26]:
# 布尔型数据过滤数据
loan_data[loan_data['grade']=='A']

loan_amnt grade sub_grade emp_length home_ownership  annual_inc  \
3     14000.0     A        A4  10+ years           RENT     72000.0   
8      6000.0     A        A5  10+ years       MORTGAGE     48000.0   
18    12800.0     A        A3  10+ years       MORTGAGE    100000.0   
19     2100.0     A        A5     1 year       MORTGAGE     72000.0   
25    18000.0     A        A5    8 years       MORTGAGE     82000.0   
28    18000.0     A        A5    8 years       MORTGAGE     82000.0   
29        NaN     A        A4  10+ years           RENT     58000.0   
31    12000.0     A        A5     1 year           RENT    105000.0   
32     5000.0     A        A4    9 years            OWN     56400.0   
38    15000.0     A        A5  10+ years       MORTGAGE     55000.0   
41    14000.0     A        A3  10+ years            OWN     71000.0   
43     6600.0     A        A5    8 years       MORTGAGE     55800.0   
46     2000.0     A        A1        n/a            OWN     16000.0   
49     6000.0     A        A5    8 years           RENT     82000.0   
54     6000.0     A        A5    8 years           RENT     82000.0   
64     8000.0     A        A4    5 years       MORTGAGE     38000.0   
65     2000.0     A        A2    2 years       MORTGAGE     44000.0   

       issue_d  loan_status  open_acc   total_pymnt  total_rec_int  
3   2017/11/11   fully Paid         6  15099.982530        1099.98  
8    2017/9/11   Fully Paid        11   7235.598134        1235.60  
18   2017/4/11   Fully Paid        10  14211.312910        1411.31  
19   2017/4/11   Fully Paid        15   2357.178487         257.18  
25   2017/4/11   Fully Paid         8  20204.461240        2204.46  
28   2017/4/11   Fully Paid         8  20204.461240        2204.46  
29   2017/1/11   Fully Paid        12  10994.614810         994.61  
31   2017/1/11   Fully Paid        10  13041.191490        1041.19  
32   2017/1/11  Charged Off        15   3927.470000         465.75  
38  2017/10/10   Fully Paid        14  16274.762910        1274.76  
41  2017/10/10   fully Paid         8  15595.389910        1595.39  
43   2017/7/10   Fully Paid         8   7349.816860         749.82  
46   2017/7/10   Fully Paid         9   2203.348430         203.35  
49   2017/5/10   Fully Paid        17   6745.258045         745.26  
54   2017/5/10   Fully Paid        17   6745.258045         745.26  
64   2017/11/9   Fully Paid         6   8322.639678         322.64  
65   2017/11/9   Fully Paid        11   2207.212632         207.21

In [6]:
# 只选择其中特定的类型进行处理，如数字编码
print(loan_data.select_dtypes(include=['object']).head(2))

  grade sub_grade emp_length home_ownership     issue_d  loan_status
0     B        B2  10+ years           RENT  2017/12/11   Fully Paid
1     C        C4   < 1 year           RENT  2017/12/11  Charged Off


In [8]:
loan_object = loan_data.select_dtypes(include=['object'])# 选择指定类型的列

In [11]:
print(loan_object.sort_values('grade',ascending=False))# 按照指定列排序

   grade sub_grade emp_length home_ownership     issue_d    loan_status
4      F        F5    4 years       MORTGAGE  2017/10/11     Fully Paid
20     F        F2    9 years           RENT   2017/4/11    Charged Off
56     E        E1  10+ years           RENT   2017/5/10     Fully Paid
51     E        E1  10+ years           RENT   2017/5/10     Fully Paid
27     E        E1  10+ years           RENT   2017/3/11     Fully Paid
26     E        E1     1 year       MORTGAGE   2017/4/11     Fully Paid
24     E        E1  10+ years           RENT   2017/3/11     Fully Paid
23     E        E1     1 year       MORTGAGE   2017/4/11     Fully Paid
34     D        D5   < 1 year           RENT   2017/1/11     Fully Paid
15     D        D2    4 years           RENT   2017/5/11    Charged Off
58     D        D2    2 years           RENT   2017/4/10     Fully Paid
47     D        D4  10+ years       MORTGAGE   2017/7/10     fully Paid
37     D        D3   < 1 year       MORTGAGE   2017/5/11    Char

### 4 汇总及描述性统计

In [12]:
loan_data.shape# 数据框的行列数 shape

(68, 11)

In [48]:
print(loan_data.head(1))# 数据框的前几行，后几行
print(loan_data.tail(1))

   loan_amnt grade sub_grade emp_length home_ownership  annual_inc  \
0     5000.0     B        B2  10+ years           RENT     24000.0   

      issue_d loan_status  open_acc  total_pymnt  total_rec_int  
0  2017/12/11  Fully Paid         3  5863.155187         863.16  
    loan_amnt grade sub_grade emp_length home_ownership  annual_inc  \
67    17600.0     D        D4    8 years           RENT     72000.0   

      issue_d loan_status  open_acc  total_pymnt  total_rec_int  
67  2017/5/11  Fully Paid        14  20172.78686        2572.79  


In [16]:
r = loan_data['grade'].value_counts()# Series 的唯一值个数 value_counts
print(r)
print(type(r))

B    18
A    17
C    14
D    11
E     6
F     2
Name: grade, dtype: int64
<class 'pandas.core.series.Series'>


In [52]:
print(loan_data.info()) # 数据框信息

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 11 columns):
loan_amnt         66 non-null float64
grade             68 non-null object
sub_grade         68 non-null object
emp_length        68 non-null object
home_ownership    68 non-null object
annual_inc        65 non-null float64
issue_d           68 non-null object
loan_status       68 non-null object
open_acc          68 non-null int64
total_pymnt       68 non-null float64
total_rec_int     68 non-null float64
dtypes: float64(4), int64(1), object(6)
memory usage: 5.9+ KB
None


In [17]:
print(loan_data.describe()) # 描述性统计信息汇总

           loan_amnt     annual_inc   open_acc   total_pymnt  total_rec_int
count      66.000000      65.000000  68.000000     68.000000      68.000000
mean    19913.257576   73199.676923   9.264706  14637.408621    2965.349559
std     60650.680480   65755.454700   3.815200  11882.493935    3569.197500
min      1800.000000   16000.000000   2.000000   1014.530000     203.350000
25%      6000.000000   45600.000000   7.000000   6543.590000     988.145000
50%     11000.000000   63000.000000   9.000000  10819.285650    1612.175000
75%     17600.000000   82000.000000  11.250000  19901.630490    3046.635000
max    500000.000000  550000.000000  19.000000  48845.292210   14124.860000


In [20]:
print(loan_data.cov()) # 协方差矩阵

                  loan_amnt    annual_inc      open_acc   total_pymnt  \
loan_amnt      3.678505e+09 -3.274485e+07 -19247.109557  1.396036e+08   
annual_inc    -3.274485e+07  4.323780e+09  -8030.857212  1.537413e+08   
open_acc      -1.924711e+04 -8.030857e+03     14.555751  6.464778e+03   
total_pymnt    1.396036e+08  1.537413e+08   6464.778351  1.411937e+08   
total_rec_int  2.674619e+07  3.458975e+07   1693.108477  3.868748e+07   

               total_rec_int  
loan_amnt       2.674619e+07  
annual_inc      3.458975e+07  
open_acc        1.693108e+03  
total_pymnt     3.868748e+07  
total_rec_int   1.273917e+07  


In [22]:
print(loan_data.corr())# 相关系数矩阵

               loan_amnt  annual_inc  open_acc  total_pymnt  total_rec_int
loan_amnt       1.000000   -0.007904 -0.082313     0.191863       0.122136
annual_inc     -0.007904    1.000000 -0.032187     0.193778       0.144707
open_acc       -0.082313   -0.032187  1.000000     0.142603       0.124336
total_pymnt     0.191863    0.193778  0.142603     1.000000       0.912205
total_rec_int   0.122136    0.144707  0.124336     0.912205       1.000000


### 5 文件读写

In [63]:
loan_skip10 = pd.read_csv('./input/loandata.csv',skiprows=10) # 跳过前多少行

In [66]:
loan_10 = pd.read_csv('./input/loandata.csv',nrows=10)# 指定行数 nrows

In [69]:
loan_10_encode = pd.read_csv('./input/loandata.csv',nrows=10,encoding='utf-8')# 指定行数 nrows以及编码方式

In [26]:
# 中等数量级数据读写及操作 chunksize
chunker = pd.read_csv('./data/loandata.csv',chunksize=20)
for chunk in chunker:
    print(sum(chunk.memory_usage(deep='True'))/1024)

8.3271484375
8.330078125
8.2685546875
3.3740234375


In [27]:
print(loan_data.memory_usage())# 文件占用内存情况分析 
print(sum(loan_data.memory_usage())/1024)

Index              80
loan_amnt         544
grade             544
sub_grade         544
emp_length        544
home_ownership    544
annual_inc        544
issue_d           544
loan_status       544
open_acc          544
total_pymnt       544
total_rec_int     544
dtype: int64
5.921875


In [94]:
print(loan_data.memory_usage(deep=True)# 文件占用内存情况分析 deep
print(sum(loan_data.memory_usage(deep=True))/1024

Index               72
loan_amnt          544
grade             3128
sub_grade         3196
emp_length        3581
home_ownership    3441
annual_inc         544
issue_d           3682
loan_status       3759
open_acc           544
total_pymnt        544
total_rec_int      544
dtype: int64
23


In [162]:
# 用字典的方式指定某一列的特定值为缺失NaN，使得能够识别
map_id = {'grade':'A'}
loan_A_miss = pd.read_csv('./input/loandata.csv',na_values=map_id)

### 6 ndarray、Series和DataFrame的相互转换

In [114]:
array_1d = np.array([2,3,4])
ser_1d = pd.Series(array_1d, index=list('ABC')) # 一维array转换成Series
print(ser_1d)

A    2
B    3
C    4
dtype: int64

In [113]:
array_2d = np.array([[2,3,4],[11,12,13]])#二维array转换成DataFrame
df_2d = pd.DataFrame(array_2d,index=['a','b'],columns=['A','B','C'])
df_2d

A   B   C
a   2   3   4
b  11  12  13

In [124]:
pd.DataFrame(ser_1d,columns=['a']) # Series转换成DataFrame

a
A  2
B  3
C  4

In [129]:
print(np.array(df_2d))# DataFrame转换成ndarray
print(df_2d.values)

[[ 2  3  4]
 [11 12 13]]
[[ 2  3  4]
 [11 12 13]]


### 7 特征离散化

In [30]:
amnt_series = loan_data['loan_amnt']
# 指定区间长度的离散化
print(amnt_series.value_counts())

bins = [0, 1000, 2000, 4000, 8000, 100000]
cut = pd.cut(amnt_series, bins, labels=['a', 'b', 'c', 'd', 'e'])
print(cut)


6000.0      6
8000.0      6
12000.0     5
5000.0      4
4000.0      4
25000.0     3
35000.0     3
2000.0      2
30000.0     2
14000.0     2
7000.0      2
1800.0      2
17600.0     2
18000.0     2
20000.0     2
12400.0     1
2500.0      1
16000.0     1
24175.0     1
500000.0    1
9000.0      1
13000.0     1
15000.0     1
12800.0     1
2100.0      1
7200.0      1
6600.0      1
27000.0     1
17325.0     1
12500.0     1
24250.0     1
14125.0     1
7500.0      1
10000.0     1
Name: loan_amnt, dtype: int64
0       d
1       c
2       e
3       e
4       e
5       e
6       e
7       d
8       d
9       e
10      c
11      d
12      e
13      e
14      e
15      e
16      e
17      d
18      e
19      c
20      e
21      d
22      e
23      e
24      e
25      e
26      e
27      e
28      e
29    NaN
     ... 
38      e
39      d
40      d
41      e
42      d
43      d
44      e
45    NaN
46      b
47      e
48      b
49      d
50      d
51      e
52      c
53      b
54      d
55      d
56  

In [31]:
# 等频离散化
cuts = pd.qcut(amnt_series,4,labels=['a','b','c','d'])
cuts.value_counts()

a    20
c    17
d    16
b    13
Name: loan_amnt, dtype: int64

### 8 缺失值填补与离群值处理

#### 8.1 查看数据集的各个属性是否存在缺失值，并统计缺失值数量

In [39]:
print(loan_data.isnull()==False)# 判断每一个数据是否为缺失值

    loan_amnt  grade  sub_grade  emp_length  home_ownership  annual_inc  \
0        True   True       True        True            True        True   
1        True   True       True        True            True        True   
2        True   True       True        True            True        True   
3        True   True       True        True            True        True   
4        True   True       True        True            True        True   
5        True   True       True        True            True       False   
6        True   True       True        True            True        True   
7        True   True       True        True            True        True   
8        True   True       True        True            True        True   
9        True   True       True        True            True        True   
10       True   True       True        True            True        True   
11       True   True       True        True            True        True   
12       True   True     

In [40]:
loan_data.isnull().any() # 存在缺失值的列是那些

loan_amnt          True
grade             False
sub_grade         False
emp_length         True
home_ownership    False
annual_inc         True
issue_d           False
loan_status       False
open_acc          False
total_pymnt       False
total_rec_int     False
dtype: bool

In [150]:
np.sum(loan_data.isnull(), axis=0)  # 统计每一行缺失值的数量

loan_amnt         2
grade             0
sub_grade         0
emp_length        0
home_ownership    0
annual_inc        3
issue_d           0
loan_status       0
open_acc          0
total_pymnt       0
total_rec_int     0
dtype: int64

In [41]:
loan_data.isnull().values == True

array([[False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, Fal

In [46]:
print(loan_data[loan_data.isnull().values]) # 展示存在缺失值的行

    loan_amnt grade sub_grade emp_length home_ownership  annual_inc  \
5     16000.0     C        C2  10+ years            OWN         NaN   
29        NaN     A        A4  10+ years           RENT     58000.0   
36    10000.0     C        C2    2 years       MORTGAGE         NaN   
45        NaN     B        B5    8 years       MORTGAGE     62400.0   
46     2000.0     A        A1        NaN            OWN     16000.0   
60     4000.0     B        B2    2 years           RENT         NaN   

       issue_d  loan_status  open_acc   total_pymnt  total_rec_int  
5   2017/10/11  Charged Off        13   9202.000000        3800.05  
29   2017/1/11   Fully Paid        12  10994.614810         994.61  
36   2017/9/10   Fully Paid        10  13181.651550        3181.65  
45   2017/8/10  Charged Off         8   5207.370000        1520.88  
46   2017/7/10   Fully Paid         9   2203.348430         203.35  
60   2017/5/10   Fully Paid         3   4318.218537         318.22  


#### 8.2 删除缺失值

In [50]:
from copy import deepcopy
loan_data_miss = deepcopy(loan_data)
#print(loan_data_miss)
# 舍弃缺失值 dropna 并指定方法 how   ,any :只要有一列为None就删除这一行数据
print(loan_data_miss.dropna(how='any',axis=0))

# inplace=True 在原DataFrame上做更改
loan_data_miss.dropna(how='any',inplace=True)

    loan_amnt grade sub_grade emp_length home_ownership  annual_inc  \
0      5000.0     B        B2  10+ years           RENT     24000.0   
1      2500.0     C        C4   < 1 year           RENT     30000.0   
2     12500.0     D        D4  10+ years           RENT     74400.0   
3     14000.0     A        A4  10+ years           RENT     72000.0   
4     35000.0     F        F5    4 years       MORTGAGE    100000.0   
6     14125.0     B        B5  10+ years            OWN     60000.0   
7      5000.0     B        B2    4 years           RENT     49000.0   
8      6000.0     A        A5  10+ years       MORTGAGE     48000.0   
9     12000.0     C        C3   < 1 year       MORTGAGE     81996.0   
10     4000.0     D        D4  10+ years       MORTGAGE     40000.0   
11     8000.0     B        B4     1 year           RENT     42000.0   
12    27000.0     D        D5    6 years       MORTGAGE     83004.0   
13    25000.0     C        C4  10+ years           RENT     79000.0   
14    

#### 8.3 填补缺失值

In [52]:
# 填充缺失值 fillna

# 通过字典指定每一列的填充方式
loan_data_fill = loan_data.fillna({'loan_amnt':'缺失值','annual_inc':'缺失值'})
print(loan_data_fill)

   loan_amnt grade sub_grade emp_length home_ownership annual_inc     issue_d  \
0       5000     B        B2  10+ years           RENT      24000  2017/12/11   
1       2500     C        C4   < 1 year           RENT      30000  2017/12/11   
2      12500     D        D4  10+ years           RENT      74400  2017/11/11   
3      14000     A        A4  10+ years           RENT      72000  2017/11/11   
4      35000     F        F5    4 years       MORTGAGE     100000  2017/10/11   
5      16000     C        C2  10+ years            OWN        缺失值  2017/10/11   
6      14125     B        B5  10+ years            OWN      60000  2017/10/11   
7       5000     B        B2    4 years           RENT      49000   2017/9/11   
8       6000     A        A5  10+ years       MORTGAGE      48000   2017/9/11   
9      12000     C        C3   < 1 year       MORTGAGE      81996  2017/10/11   
10      4000     D        D4  10+ years       MORTGAGE      40000   2017/6/11   
11      8000     B        B4

针对属性`loan_amount`

+ 使用`total_pymnt`属性和total_tec_int属性的差值作为要填补的值。除了利息以外还可能包括逾期费，手续费和罚息等费用，只能近似获得一个实际贷款的金额，并对填补的值作格式转换

In [67]:
loan_data['loan_amnt'] = loan_data['loan_amnt'].fillna(loan_data['total_pymnt'] - loan_data['total_rec_int']).astype('int')
loan_data.to_csv("data/b.csv")



针对属性`annual_inc`

+ 在数据集中没有其他属性作参考，选择用现有数据的均值进行填补

In [68]:
mean_val = loan_data['annual_inc'].mean()
loan_data['annual_inc'] = loan_data['annual_inc'].fillna(mean_val)
loan_data.to_csv("data/b.csv")

In [73]:
example = pd.DataFrame([0,np.nan,3,2])
print(example)
example = example.fillna(method='ffill')# 前向或后向填补,时间序列场景
print(example)

     0
0  0.0
1  NaN
2  3.0
3  2.0
     0
0  0.0
1  0.0
2  3.0
3  2.0


#### 8.4 离群值处理

In [76]:
print(loan_data.describe().astype(np.int64).T)

               count   mean    std    min    25%    50%    75%     max
loan_amnt         68  19528  59782   1800   6000  10000  17600  500000
annual_inc        68  73199  64266  16000  47400  64000  82000  550000
open_acc          68      9      3      2      7      9     11      19
total_pymnt       68  14637  11882   1014   6543  10819  19901   48845
total_rec_int     68   2965   3569    203    988   1612   3046   14124


In [12]:
new_loan_data = loan_data.replace(500000,loan_data['loan_amnt'].mean())

In [13]:
loan_data.describe().astype(np.int64).T

count   mean    std    min    25%    50%    75%     max
loan_amnt         68  19528  59782   1800   6000  10000  17600  500000
annual_inc        68  73199  64266  16000  47400  64000  82000  550000
open_acc          68      9      3      2      7      9     11      19
total_pymnt       68  14637  11882   1014   6543  10819  19901   48845
total_rec_int     68   2965   3569    203    988   1612   3046   14124

#### 8.5 类型转换

In [36]:
loan_data['issue_d']=pd.to_datetime(loan_data['issue_d']) # 转换为datetime类型
loan_data.dtypes

loan_amnt                float64
grade                     object
sub_grade                 object
emp_length                object
home_ownership            object
annual_inc               float64
issue_d           datetime64[ns]
loan_status               object
open_acc                   int64
total_pymnt              float64
total_rec_int            float64
dtype: object

#### 练习：对属性`loan_status`的取值，统计频次会发现：由于空格，相同的贷款状态被“误认为”是不同的类别，这会造成统计结果不可用。因此，需要解决属性中存在空格的问题。

In [180]:
loan_data['loan_status'].value_counts()

Fully Paid       48
Charged Off       8
fully Paid        5
 Fully Paid       4
   Fully Paid     1
charged Off       1
  Charged Off     1
Name: loan_status, dtype: int64

In [78]:
loan_data['loan_status'] = loan_data['loan_status'].map(str.strip) #q去除先后空格
loan_data['loan_status'] = loan_data['loan_status'].map(str.title)
loan_data['loan_status'].value_counts()

0      Fully Paid
1     Charged Off
2      Fully Paid
3      Fully Paid
4      Fully Paid
5     Charged Off
6      Fully Paid
7      Fully Paid
8      Fully Paid
9      Fully Paid
10     Fully Paid
11    Charged Off
12     Fully Paid
13     Fully Paid
14     Fully Paid
15    Charged Off
16     Fully Paid
17    Charged Off
18     Fully Paid
19     Fully Paid
20    Charged Off
21     Fully Paid
22    Charged Off
23     Fully Paid
24     Fully Paid
25     Fully Paid
26     Fully Paid
27     Fully Paid
28     Fully Paid
29     Fully Paid
         ...     
38     Fully Paid
39     Fully Paid
40     Fully Paid
41     Fully Paid
42     Fully Paid
43     Fully Paid
44     Fully Paid
45    Charged Off
46     Fully Paid
47     Fully Paid
48     Fully Paid
49     Fully Paid
50     Fully Paid
51     Fully Paid
52     Fully Paid
53     Fully Paid
54     Fully Paid
55     Fully Paid
56     Fully Paid
57     Fully Paid
58     Fully Paid
59     Fully Paid
60     Fully Paid
61     Fully Paid
62     Ful

Fully Paid     58
Charged Off    10
Name: loan_status, dtype: int64

### 9 数据融合和分组

In [57]:
# concat,merge 见cheatsheet

根据开户数量的多少对用户进行分级，也就是对属性`open_acc`进行分组

+ 6个账户以下为A级，6-12个账户为B级，12-18个账户为C级，18-24个账户为D级


In [81]:
bins = [0, 6, 12, 18, 24]

group_names = ['A', 'B', 'C', 'D']

new_loan_data['categories'] = pd.cut(new_loan_data['open_acc'], bins, labels=group_names)

NameError: name 'new_loan_data' is not defined

In [15]:
new_loan_data

loan_amnt grade sub_grade emp_length home_ownership     annual_inc  \
0    5000.000000     B        B2  10+ years           RENT   24000.000000   
1    2500.000000     C        C4   < 1 year           RENT   30000.000000   
2   12500.000000     D        D4  10+ years           RENT   74400.000000   
3   14000.000000     A        A4  10+ years           RENT   72000.000000   
4   35000.000000     F        F5    4 years       MORTGAGE  100000.000000   
5   16000.000000     C        C2  10+ years            OWN   73199.676923   
6   14125.000000     B        B5  10+ years            OWN   60000.000000   
7    5000.000000     B        B2    4 years           RENT   49000.000000   
8    6000.000000     A        A5  10+ years       MORTGAGE   48000.000000   
9   12000.000000     C        C3   < 1 year       MORTGAGE   81996.000000   
10   4000.000000     D        D4  10+ years       MORTGAGE   40000.000000   
11   8000.000000     B        B4     1 year           RENT   42000.000000   
12  27000.000000     D        D5    6 years       MORTGAGE   83004.000000   
13  25000.000000     C        C4  10+ years           RENT   79000.000000   
14  17600.000000     D        D4    8 years           RENT   72000.000000   
15  20000.000000     D        D2    4 years           RENT   40000.000000   
16  12400.000000     C        C2  10+ years           RENT   65000.000000   
17   6000.000000     D        D3   < 1 year       MORTGAGE   60000.000000   
18  12800.000000     A        A3  10+ years       MORTGAGE  100000.000000   
19   2100.000000     A        A5     1 year       MORTGAGE   72000.000000   
20  17325.000000     F        F2    9 years           RENT   35004.000000   
21   5000.000000     C        C5  10+ years       MORTGAGE   69000.000000   
22  24175.000000     B        B5    9 years       MORTGAGE   95000.000000   
23  30000.000000     E        E1     1 year       MORTGAGE  100000.000000   
24  35000.000000     E        E1  10+ years           RENT  106000.000000   
25  18000.000000     A        A5    8 years       MORTGAGE   82000.000000   
26  30000.000000     E        E1     1 year       MORTGAGE  100000.000000   
27  35000.000000     E        E1  10+ years           RENT  106000.000000   
28  18000.000000     A        A5    8 years       MORTGAGE   82000.000000   
29  10000.000000     A        A4  10+ years           RENT   58000.000000   
..           ...   ...       ...        ...            ...            ...   
38  15000.000000     A        A5  10+ years       MORTGAGE   55000.000000   
39   8000.000000     B        B2    5 years       MORTGAGE  550000.000000   
40   7200.000000     C        C5  10+ years           RENT   68400.000000   
41  14000.000000     A        A3  10+ years            OWN   71000.000000   
42   7500.000000     B        B5     1 year           RENT   35004.000000   
43   6600.000000     A        A5    8 years       MORTGAGE   55800.000000   
44  12000.000000     C        C1    5 years           RENT   45600.000000   
45   3686.000000     B        B5    8 years       MORTGAGE   62400.000000   
46   2000.000000     A        A1        n/a            OWN   16000.000000   
47  13000.000000     D        D4  10+ years       MORTGAGE   25000.000000   
48   1800.000000     C        C3    6 years            OWN   45600.000000   
49   6000.000000     A        A5    8 years           RENT   82000.000000   
50   7000.000000     B        B3  10+ years       MORTGAGE  102660.000000   
51  25000.000000     E        E1  10+ years           RENT   56000.000000   
52   4000.000000     B        B2    2 years           RENT   16800.000000   
53   1800.000000     C        C3    6 years            OWN   45600.000000   
54   6000.000000     A        A5    8 years           RENT   82000.000000   
55   7000.000000     B        B3  10+ years       MORTGAGE  102660.000000   
56  19528.838235     E        E1  10+ years           RENT   56000.000000   
57   4000.000000     B        B2    2 years           RENT   16800.000000   
58 

根据属性`home_ownership`,对用户的年收入(属性`annual_inc`)，进行分类统计

In [85]:
# 各分组年收入中位数
group_value = loan_data['annual_inc'].groupby(loan_data['home_ownership'])
group_value.mean()

home_ownership
MORTGAGE    92309.333687
OWN         52542.810989
RENT        60400.239904
Name: annual_inc, dtype: float64

In [ ]:
# 各分组贷款数额中位数
group_value1 = loan_data['loan_amnt'].groupby(loan_data['home_ownership']) 
group_value1.max()


### 10 One-Hot编码 

In [88]:
dummies = pd.get_dummies(loan_data['grade'],prefix='grade')
pd.concat([loan_data,dummies],axis=1) # 拼接回原来的数据结构
print(loan_data)

    loan_amnt grade sub_grade emp_length home_ownership  annual_inc  \
0      5000.0     B        B2  10+ years           RENT     24000.0   
1      2500.0     C        C4   < 1 year           RENT     30000.0   
2     12500.0     D        D4  10+ years           RENT     74400.0   
3     14000.0     A        A4  10+ years           RENT     72000.0   
4     35000.0     F        F5    4 years       MORTGAGE    100000.0   
5     16000.0     C        C2  10+ years            OWN         NaN   
6     14125.0     B        B5  10+ years            OWN     60000.0   
7      5000.0     B        B2    4 years           RENT     49000.0   
8      6000.0     A        A5  10+ years       MORTGAGE     48000.0   
9     12000.0     C        C3   < 1 year       MORTGAGE     81996.0   
10     4000.0     D        D4  10+ years       MORTGAGE     40000.0   
11     8000.0     B        B4     1 year           RENT     42000.0   
12    27000.0     D        D5    6 years       MORTGAGE     83004.0   
13    

<center><font color="#888">Copyright &copy; 2017 Sid Ian@Boya, <a href="mailto:xiaodongy@boyabigdata.cn">xiaodongy@boyabigdata.cn</a>. All Rights Reserved.</font></center>