In [1]:
print( 'helloworld')

helloworld


In [2]:
import numpy as np

In [7]:
np.random.rand(2,3).dot(np.random.rand(3,2))

array([[1.0291325 , 0.97399443],
       [0.72401748, 1.09780015]])

In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [9]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
(a-1+2)/2


array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5]])